### ISSUE TITLE
Institution 'City/Town' field shows as 'City' on the portal

### ISSUE THREAD

**Issue by lmfrench** [gbif/hp-uk-collections#14]
**Describe the bug**
On GrSciColl, the address section includes a 'City/Town' field. In the DiSSCo UK portal, the column shows as 'City' - although if you click into the institutional record for more detail this then states 'City/Town' under address. (NB: it also shows as 'City' when you edit the GrSciColl record). 

**To Reproduce**
See Kew Botanic Garden as an example:
Portal view: https://uk-collections.hp.gbif-staging.org/institution/search?q=kew
GrSciColl view: https://www.gbif.org/grscicoll/institution/fa252605-26f6-426c-9892-94d071c2c77f
GrSciColl edit view: https://registry.gbif.org/institution/fa252605-26f6-426c-9892-94d071c2c77f

**Expected behavior**
We would like the column in our portal to say 'City/Town', because many of our institutions are not based in cities. 

My guess is this requires a change to [this js file](https://github.com/gbif/hp-uk-collections/blob/master/_includes/js/config.js), but I am not sure what we should enter (possibly adding ` defaultTableColumns` to `institution: {` , but I don't know if we can also use this to rename the headings)

**Screenshots**
*Portal View*
![image](https://user-images.githubusercontent.com/15875191/215768631-65431b21-5777-4a43-a533-7acb1fe8e954.png)

*GrSciColl Standard View*
![image](https://user-images.githubusercontent.com/15875191/215767695-d00c051b-0b43-4165-a98d-6c4b2089e28f.png)

*GrSciColl Edit View*
![image](https://user-images.githubusercontent.com/15875191/215770894-e208a676-0013-4733-b606-f29ae1cf5a7b.png)

**Comment by MortenHofft** [comment]
In this section you can overwrite translations. There is already one that is overwritten. Namely renaming occurrences to specimens.
https://github.com/gbif/hp-uk-collections/blob/master/_includes/js/config.js#L121

You could update that to 
```js
messages: {
    "catalogues.occurrences": "Specimens",
    "filters.city.name": "City/town"
  }
```

I believe that would do it

**Comment by lmfrench** [comment]
Thank you!
