### ISSUE TITLE
UX tweaks

### ISSUE THREAD

**Issue by benscott** [gbif/hp-uk-collections#20]
Suggestions for UX tweaks arising from chat with Vince:

On the landing page:
- can you make it clearer users should scroll down - perhaps a chevron at the bottom?
- Can a search bar be included on the top banner e.g data.nhm.ac.uk?

At smaller screen sizes, can a text break be added between UK Natural Science <br/>Collections Portal.

So it doesn't do this:  

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/81690/222715698-202d4282-bc8d-41de-8844-afb32c15af9f.png">

On the dataset table:

The apply filter looks like a sort icon: 

<img width="174" alt="image" src="https://user-images.githubusercontent.com/81690/222715956-bbb21f84-9c24-43cf-87d7-c435424829cd.png">
 
(although we noticed afterwards Outlook uses the same, so if that's now becomes standard icon for filtering ignore us)

On the dissco site:

Have a big button at the top signposting the data portal site.

**Comment by MortenHofft** [comment]
**Scrolling**
You can adjust the height of the hero image. That might be the simplest way to indicate that users can scroll? That said I believe most users these days are familiar with scrolling. 

Add e.g. `height: 700vh # set image height to 70 of viewport height`  to the font matter on the home page
https://hp-theme.gbif-staging.org/layout/hero

**Comment by MortenHofft** [comment]
**Title styling**
https://github.com/gbif/hp-uk-collections/blob/master/_sass/_main.scss#L10
It is possible to control margins, font size etc using media queries (screen sizes). 
It already does so a bit.

**Comment by MortenHofft** [comment]
**Filter icon**
It isn't something you can change. It would have to be done in the data widgets and apply to everyone.
I do not have a strong preference for that icon. Funnel is also used at times.
The sorting icon typically have the bars left or right aligned i believe.

**Comment by MortenHofft** [comment]
**Search bar**
It is possible to add a search bar to the header. But it isn't part of the theme. But you can do so by inserting html (and possible some javascript)
I believe you could just change the description to include html
https://github.com/gbif/hp-uk-collections/blob/master/home.md?plain=1#L6

Just a rough example to show the idea
```html
description: |
  <div>
        <p>Discover digitised specimens from UK natural sciences collections</p>
        <form action="/specimen">
        <input type="text" placeholder="Search" class="input"><input type="submit" class="button">
            </form>
    </div>
```
