### ISSUE TITLE
Add maps to institution search

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-uk-collections#22]
You mentioned recently that you would like to see a map of institutions, instead of the hardcoded image you have on the landing page.

https://github.com/gbif/hp-uk-collections/blob/928362142f363aa89d99d3fabad2f37e5f151c72/_includes/js/config.js#L105

By changing above line to `true` a map will be shown in institution search. For now it will only show in your staging environment, but it allows you to test it and see if it is something you would like. I will let you know when it is put into production

**Comment by lmfrench** [comment]
Thanks, this map looks good, will be happy to have this on the site once it is ready for production

**Comment by lmfrench** [comment]
I've noticed a couple of institutions which appear in the wrong location:

-  University of Aberdeen is appearing in the middle of the sea - when I check their [GrSciColl record](https://www.gbif.org/grscicoll/institution/2041e32f-a714-4912-93bb-3632651c8413) they do have a valid postcode (the postcode for one of their [herbarium collection entries ](https://www.gbif.org/grscicoll/collection/ed17f24d-c240-4ea3-8e50-1b3450559114)is not valid though)
- Cornwall College is shown in Belgium. The postcode on their [GrSciColl record](https://www.gbif.org/grscicoll/collection/916e4c05-7c32-40f9-a469-88770a271729) is valid

**Comment by MortenHofft** [comment]
The coordinates comes from the latitude longitude fields.

**Comment by MortenHofft** [comment]
> Thanks, this map looks good, will be happy to have this on the site once it is ready for production

The code is in production, so it is up to you when you want to enable it.

**Comment by lmfrench** [comment]
@ManonGros We had a look and the University of Aberdeen lat/long fields are also coming from IH. We are going to remove IH as the master source for both of those records and update it

Thanks again Morten - once we have updated those records I will make this feature live on the site, it looks great and we will share it with the DiSSCo UK network. I'll add an FAQ to the site to explain to people how to update their lat/long in GrSCiColl in case there are any other errors we haven't noticed.

**Comment by MortenHofft** [comment]
I've left a few automated suggestions for location updates, as well as a few for dead home page links
For example:
https://registry.gbif.org/institution/5856795e-02c7-49ee-9c26-dddfb7b8f68a?suggestionId=1064

Looks like I can generate coordinate suggestions for around 40 more institutions. Let me know if you would like me to do so

**Comment by ManonGros** [comment]
Hi @lmfrench, if you can forward correction to IH, I am sure it would be appreciated.
Otherwise, feel free to disconnect institution entries from IH (this shouldn't be a problem). If you need to disconnect **collection** entries from IH for one reason or another, please contact me by email. Thanks!

**Comment by lmfrench** [comment]
@MortenHofft I tried to make this feature live earlier, but it is not showing on the [site](https://data.dissco-uk.org/institution/search). It does work on the [staging site](https://uk-collections.hp.gbif-staging.org/institution/search).

This was the code I changed:
https://github.com/gbif/hp-uk-collections/blob/949bf4e8ec8f89974048f3e89f7255a47e919a09/_includes/js/config.js#L105

**Comment by lmfrench** [comment]
Thanks a lot, all working - hope you enjoyed the break!
