### ISSUE TITLE
Institution and Specimen Pages are blank

### ISSUE THREAD

**Issue by lmfrench** [gbif/hp-uk-collections#24]
**Describe the bug**
Specimen and institution pages are blank following the update to [v1.0.2](https://github.com/gbif/hp-uk-collections/releases/tag/v1.0.2)

We think this is caused by an error in the master branch version of [config.js](https://github.com/gbif/hp-uk-collections/blob/master/_includes/js/config.js#L104)
![image](https://github.com/gbif/hp-uk-collections/assets/15875191/641b2fbd-c508-4951-bd4a-1f0c598ce79d)

In my latest release, I used [a branch](https://github.com/gbif/hp-uk-collections/tree/mapupdate) which did not include the latest commits related to #22, but the new release appears to have included them anyway (even though the [comparison](https://github.com/gbif/hp-uk-collections/compare/v1.0.1...v1.0.2) between v1.0.1 and v1.0.2 does not show this). 

**To Reproduce**
Got to any of the specimen/institution pages e.g. https://data.dissco-uk.org/specimen/search?view=GALLERY

**Comment by MortenHofft** [comment]
fixed and dployed. There was a trailing comma in the json

**Comment by lmfrench** [comment]
I did test on my local version and it was working fine (couldn't test on staging because I didn't want to deploy the rest of the commits you had done for #22 since it wasn't ready yet). I think the error is in how I did the release, is it possible for me to release using a branch that is behind master?

**Comment by MortenHofft** [comment]
Ahh, yes you can do a release from another branch than master. And the code I had added in #22, would work in production as well. It just wouldn't show a map. So it wasn't a breaking change, just not functional in prod yet. Sorry - I should have been more specific.

**Comment by lmfrench** [comment]
Yeah that's what I tried to do, although it didn't work - I'm not sure if I did something wrong or if it isn't possible? (see the [comparison](https://github.com/gbif/hp-uk-collections/compare/v1.0.1...v1.0.2) between 1.0.1 and 1.0.2 which doesn't show any of the commits you had added - I'm not sure how they ended up on the live site) 

I had noticed there was an issue with the code added in #22 from viewing the staging site, which is why I had made a branch without them to update the maptile/mapbox keys. (I had been planning to post about it in the #22 thread straight after I updated our maptile keys, but it then broke on the live site anyway)

**Comment by lmfrench** [comment]
Thanks for fixing this so quickly though!
