### ISSUE TITLE
Graphics optimised for GBIF portals

### ISSUE THREAD

**Issue by TurnerAlice** [gbif/hp-uk-collections#30]
Many images and graphics currently used on [dissco-uk.org](https://www.dissco-uk.org/) are not optimized for the GBIF data portal and we have no extant icon library to speak of. 

@MortenHofft please are there any GBIF libraries of generic natural sciences images and icons that we could use for the portal please?

If not, I will go about sourcing these either from NHM or open-source libraries. Thanks,

**Comment by MortenHofft** [comment]
The website is using Bulma css for theming and so includes [font awesome](https://fontawesome.com/). So you have that available already.

I'm not aware of any generic collection of images of researchers, drawers, specimens etc. But you have a big catalogue of specimen images at your hands. The best and most expensive results would probably be to hire a photographer. It seems likely that NHM and other museums already have tons of images that could be reused though?

https://collections.beatymuseum.ubc.ca/ have found/produced very nice images I find
