### ISSUE TITLE
Change 'occurrences' in dropdown

### ISSUE THREAD

**Issue by TaraWainwright** [gbif/hp-uk-collections#44]
Change 'occurrences' in menu dropdown to 'specimen records'

Potential to also change gallery to images?

**Comment by MortenHofft** [comment]
All labels can be overwritten (unless I've missed some).

> Change 'occurrences' in menu dropdown to 'specimen records'

For the menu you control it in https://github.com/gbif/hp-uk-collections/blob/master/_data/navigation.yml 

> Potential to also change gallery to images?

you probably want to change that both in the menu and the data explorer.
For the data widgets you are already doing so for some: https://github.com/gbif/hp-uk-collections/blob/master/_includes/js/config.js#L102

**Comment by jrdh** [comment]
Fixed in https://github.com/gbif/hp-uk-collections/commit/024ff78b7badad863aefe1f411edfdf00ba14890
